package com.poorcraft.ultra.tools;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.util.List;

/**
 * Data class for asset manifest (parsed from JSON).
 * 
 * Represents the manifest.json file generated by Python asset scripts.
 */
public record AssetManifest(
    @JsonProperty("version") String version,
    @JsonProperty("generated") String generated,
    @JsonProperty("seed") int seed,
    @JsonProperty("assets") List<AssetEntry> assets
) {
    
    /**
     * Individual asset entry in manifest.
     */
    public record AssetEntry(
        @JsonProperty("name") String name,
        @JsonProperty("category") String category,
        @JsonProperty("path") String path,
        @JsonProperty("width") int width,
        @JsonProperty("height") int height,
        @JsonProperty("sha256") String sha256
    ) {
        public AssetEntry {
            if (name == null || name.isBlank()) {
                throw new IllegalArgumentException("Asset name cannot be null or blank");
            }
            if (category == null || category.isBlank()) {
                throw new IllegalArgumentException("Asset category cannot be null or blank");
            }
            if (path == null || path.isBlank()) {
                throw new IllegalArgumentException("Asset path cannot be null or blank");
            }
            if (width <= 0 || height <= 0) {
                throw new IllegalArgumentException("Asset dimensions must be positive");
            }
            if (sha256 == null || sha256.length() != 64) {
                throw new IllegalArgumentException("Asset SHA-256 hash must be 64 hex characters");
            }
        }
    }
    
    public AssetManifest {
        if (version == null || version.isBlank()) {
            throw new IllegalArgumentException("Manifest version cannot be null or blank");
        }
        if (assets == null) {
            throw new IllegalArgumentException("Manifest assets list cannot be null");
        }
    }
    
    /**
     * Parse manifest from JSON string.
     * 
     * @param json JSON string to parse
     * @return Parsed AssetManifest
     * @throws IllegalArgumentException if JSON is invalid or missing required fields
     */
    public static AssetManifest fromJson(String json) {
        ObjectMapper mapper = new ObjectMapper();
        
        try {
            AssetManifest manifest = mapper.readValue(json, AssetManifest.class);
            
            // Validate parsed manifest
            if (manifest == null) {
                throw new IllegalArgumentException("Failed to parse manifest JSON");
            }
            
            return manifest;
        } catch (IOException e) {
            throw new IllegalArgumentException("Invalid manifest JSON: " + e.getMessage(), e);
        }
    }
}
